
# SEO settings
title: Simplest
description: "A developer's journey"
keywords: "Jekyll, theme, free, download, SEO, blog, web"
url: http://marioaae.io
# baseurl: "/"
baseurl: null

google_analytics: 00000000
repo: http://github.com/nandomoreirame/simplest
disqus_shortname: "nandothemes"

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 4
paginate_path: "/page/:num/"
comments: true

source: source
destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : Mario Alvarez
  job      : Software Engineer
  bio      : "Full Stack Web Developer, coffee and good food""
  thumb    : /images/
  email    : temporal@gmail.com
  url      : http://marioaae.io
  github   : http://github.com/marioaae
  twitter  : http://twitter.com/marioaae
  linkedin : http://linkedin.com/in/marioaae

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@marioaae"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
